// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7b088f62189905b998473b81c2331fd3"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"07bf76378c88abdaa6f6279178a74b28": "1f8b08000000000000ff8c9141afa2301cc4cffc3fc51c888103103d92904856764d56c0d8f5b02753695122b486e2eec1f8dd3774dd354fdf4bdea54d9be9ef3f3365cb6cb54aa27da3a23d3747a265ca76ebf4cbf7cdcc8913b89e39cab645a5bb8e2b81e017cebc3af5339f886df3bc2cb2cdae48f30c7182eb1521bb749d56b22f782771bbfd53ed16d99ae1c1ab1b25e07a6f10be4f2963d90f86f849c88d9183f18978dbc62fcf22eb48d84d8ac09ec283c698e9594bf4deed83697dfae4ccbb93687a04e79142ce48bb34ad40a0e1cee17af3af7e646cd4f0a0893e69699cf337a24f4dad84acf1a89b1cd7937daffb7bc3f8cd0d941e50eb8b12d00a673e1c31fe4263a0a4145260d0e8f849fe6f482ad1d4e454afe56232c1b7723a9de6e562bbca12cb1be71085eb6559fc8c51b5922bb26bfc21e36eceaafe040000ffff94c3da2f3d020000",
		"215e3cf9e27fb979ef10ff27f68b300f": "1f8b08000000000000ffcacd4f29cd4955a8ae56d0f3cd4ff14bcc4d55a8ad05040000ffffa2e211e515000000",
		"54928eced2dca3a3ac53767040663e39": "1f8b08000000000000ff24cb41aac4200c06e0bda7f869f795b7f536799ad64035a589656098bb0f83eb8f6f855731888160d4ae9361a335edc8da7739b0cbc9618531a3ba5f96623cc4ebf8dfb2b658e891a28fe41a675b671b37b9680f0fdf26da13fe029d42c696f0fe041d7e0d2f72272cdb8c5c96c02fce3fff060000ffffc292f88095000000",
		"81d0d8c01656e9f3a0d920eed9610026": "1f8b08000000000000ff54ceb16ac4300c80e1d97a0aa12986c3868e850e2d746c973e81e39313d373142c3b0d94be7b496eba51487cbfd610bfc3c458425e007259a5361cc0902801189a729bfbe8a2147f0d5bbeca96e3ecb597220b3dee27197b4ae126fe40abdf9e082c40ea4b3cf9c1e22f18eff14d768c616dbdb2629b1953beb1a2a47308aadc145b650633ca8ecf2f7882ee937f06fa3ad387411724e7fcfd9e2c1851f7bee736dcbf731f4753d4bdd6492f38ca6e2dfcc17f000000ffff5eccce02f1000000",
		"906ec5af0a8094a9d412299a6fa003ce": "1f8b08000000000000ff8490c16aec300c45f7fe8abb7c0f86645fe82f74d376514a6134b11a0b122b58723a61987f2ff1d0ae5aea9dc545e7e83ed679d60c3ed3bc4c8c484e588aae12b9a0f0a2e1feaf17c253126b6113d7b221a9b981f07ab9a0bb11b83cd0ccb85edffe25f7c5eefa7e144ff5d40d3af7915689baca907a6bf1ffcd247c997421bc688564739a26f8cefbb624c3f107d01194233c71c64019d578fffc12e5330fd5e934315cc3cd0164c66e5d08cf2679c4a818d90fd8b4b68d4dc0646f6fe5b2b502f0219eb072d9e71cdb15079caa63a64c234748068581b3179af04e964473f7190000ffff0273d17886010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon scaffold template", "../../templates/scaffold")
		b.SetResolver("Makefile", packr.Pointer{ForwardBox: gk, ForwardPath: "07bf76378c88abdaa6f6279178a74b28"})
		b.SetResolver("README.md", packr.Pointer{ForwardBox: gk, ForwardPath: "906ec5af0a8094a9d412299a6fa003ce"})
		b.SetResolver("assets/summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "54928eced2dca3a3ac53767040663e39"})
		b.SetResolver("go.mod", packr.Pointer{ForwardBox: gk, ForwardPath: "215e3cf9e27fb979ef10ff27f68b300f"})
		b.SetResolver("{{.SummonerName}}/summon.go", packr.Pointer{ForwardBox: gk, ForwardPath: "81d0d8c01656e9f3a0d920eed9610026"})
	}()

	return nil
}()
