
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:

      - checkout
      - run: make

      - add_ssh_keys:
          fingerprints:
            - f4:3f:d8:d7:4f:53:e9:2f:03:55:e9:28:8d:7e:dc:bc

      - run: make update-coverage-badge
