// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "0990ce45ecdd6b0f056e248fe59b181f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"07bf76378c88abdaa6f6279178a74b28": "1f8b08000000000000ff8c914f6bc24010c5cf994f31071173c806730c040c3554a849c4ad879e6493ddc4c5fd23c67811bf7b4962916a855ef6cff0e637ef3174912c97915f48e317acd9012c62ba5dc56f1febc009231c4d9a9d500a4bab35331cbd331e58b93f062e00dda4699e25eb6d16a70986115e2e4868abb535e298312df07afd516de7c98ae29d5749c37134f985705d88294d3e29860f42d634e2d4b8004ca9f0a9cdef1df1fe12dceb7fa4b6d8657ad402fc55bd337b9f2e3833bde7f288dea1a380533e9bc5f118bb21ad541c3d8b84f8a319367d7c525b807fdaec660fb15d9095e1a2c2fb0ac0a92dd6e2845e8bb53cedda829456fbb52ddaaa62ca0e4cff1c0c8f0084e1b27ae9f73d9f4ea7693edf2c93c89adb2601c86a91675f21964a3003fd19be640c4d37ed77000000ffff91583ae73e020000",
		"54928eced2dca3a3ac53767040663e39": "1f8b08000000000000ff24cb41aac4200c06e0bda7f869f795b7f536799ad64035a589656098bb0f8ceb8f6f855731888160d4ae9361a335edc8da7739b0cbc9618531a3ba5f96623cc4ebf8dfb2b658e891a28fe41a675b671b37b9680f0fdf26da13fe029d42c696f0fe041d7e0d2f72272cdb8c5c96c02fce3fff060000ffff9d5d3d4796000000",
		"7e377bec1b98fe3bd1971eb9735522e3": "1f8b08000000000000ffcacd4f29cd4955a8ae56d0f3cd4ff14bcc4d55a8add5afaed60b2ecdcdcdcf4b2d0209d5d602020000ffff2cce024527000000",
		"906ec5af0a8094a9d412299a6fa003ce": "1f8b08000000000000ff7490314b04311085fbfc8a572a1cbbbd60676da31622c2cd6d86646037736426abc771ff5d3687565eba301fef7d332f6d59b4e0899c70acba4ae48aca470d8fb75e08af59ac4326aef584ace606c2c7f98ce19ac8f59916c6e5f27997dd8ff6308e493cb7c330e932465a25ea2a531eade3f788e4147e0d8610deb5418a39cd337cebfbb323c3fe9fa23da84478e682890a9af1f6b981f2374fcde930335cc3d50164c66e43086f2625212912fb0e276d3db10b986801af5c4f70aa89bddf015fe2192bd76dccb12fb3c3a139162a9438420a284c5cbcd28c592772d132849f000000ffff58dad12a7f010000",
		"cb35e626a2c5a9c15406259f882a5aa2": "1f8b08000000000000ff54ceb16ac4300c80e1d97a0aa12986c3868e850e2d746c973e81e39313d373142c3b0d94be7b496eba51487cbfd610bfc3c458425e007259a5361cc0902801189a729bfbe8a2147f0d5bbeca96e3ecb597220b3dee27197b4ae126fe40abdf9e082c40ea4b3cf9c1e22f18eff14d768c616dbdb2629b1953beb1a2a47308aadc145b650633ca8ecf2f7882ee937f06fa3ad387411724e7fcfd9e2c1851f7bee736dcbf731f4753d4bdd6492f38ca6e2dfcc17f000000ffff5eccce02f1000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon scaffold template", "../../templates/scaffold")
		b.SetResolver("Makefile", packr.Pointer{ForwardBox: gk, ForwardPath: "07bf76378c88abdaa6f6279178a74b28"})
		b.SetResolver("README.md", packr.Pointer{ForwardBox: gk, ForwardPath: "906ec5af0a8094a9d412299a6fa003ce"})
		b.SetResolver("assets/summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "54928eced2dca3a3ac53767040663e39"})
		b.SetResolver("{{.SummonerName}}/go.mod", packr.Pointer{ForwardBox: gk, ForwardPath: "7e377bec1b98fe3bd1971eb9735522e3"})
		b.SetResolver("{{.SummonerName}}/summon{{.go}}", packr.Pointer{ForwardBox: gk, ForwardPath: "cb35e626a2c5a9c15406259f882a5aa2"})
	}()

	return nil
}()
