// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "0990ce45ecdd6b0f056e248fe59b181f"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"07bf76378c88abdaa6f6279178a74b28": "1f8b08000000000000ff8c914d6fb2401485d7dc5f7117c6c802882c494824afe435a98071eaa22b3330034e9c0f03e2c6f8df1b061b536d936ee62be73ef7dc336495aed771500a1d94b43b00ac12b2df24ffdeb6a113c5389975072e25564629aa197a173cd1ead8862e00d9655991a7db7d9e642946315eafe8935e29a3799b53c5f176fb52ed97e986e083570bcd7032fb86705d480849df09464f42da75fcdcb90054cae8a52cb08e98dd38f3eccd6f0c0e333d6b017e7a7d30ad4f179c853a32d1a2771a28e00cb45e48869ec1c9e2d54167a7f61b03f0477743cb715a1744ad19aff191bc6dd8f0337a3d36e27ce84bbf322a684cd9d7359566640697703c84c035133538d56ba6389de2ff623e9f67c572b74e63a3ef1f08e06f5645fe11612539d560d7e857c65874d73aad42afad876c3e030000ffff5ad211ca40020000",
		"215e3cf9e27fb979ef10ff27f68b300f": "1f8b08000000000000ffcacd4f29cd4955a8ae56d0f3cd4ff14bcc4d55a8ad05040000ffffa2e211e515000000",
		"54928eced2dca3a3ac53767040663e39": "1f8b08000000000000ff24cb41aac4200c06e0bda7f869f795b7f536799ad64035a589656098bb0f8ceb8f6f855731888160d4ae9361a335edc8da7739b0cbc9618531a3ba5f96623cc4ebf8dfb2b658e891a28fe41a675b671b37b9680f0fdf26da13fe029d42c696f0fe041d7e0d2f72272cdb8c5c96c02fce3fff060000ffff9d5d3d4796000000",
		"906ec5af0a8094a9d412299a6fa003ce": "1f8b08000000000000ff7491c1ab133110c6eff92bbea382cdde1f7850044f7ad18b8890e966da0c66334b32db6729fddfa5d9f689b02fa724fce69b6fe6fbb64c93167c2223cc554f12b9a2f2aceefd6bc7b9ef495a879a98d63392366b20fcbc5ce05745ae5f69625cafbfde24b3b93d0dc3512c2d7b3fea34443a49d4938c69681d7f8b4846eee1c03bf7431748694639c36efd5edc5143d868149e9c0b21b8a3bed4dda82f1aefc070b9fc5773bd76de7d281196b860697cbb6cab83fff0b818ed33c314ab6d506b6ccd3b77df63683af1aeff0664f9cd687af7b5218a7ff46ae5e319910fb4647bf7e8f02c39af031513b2d5612f8194fef02bc9714094ca638f844a44655b6a8158c34c963c7a6e2315ec197ae25a257279c8046a7d987b227ed47290a33fd394030e92195a5770a701874c47efdc67364c5a1989f38c67b1b4b93dec52f07f030000ffff2388fab36b020000",
		"cb35e626a2c5a9c15406259f882a5aa2": "1f8b08000000000000ff54ceb16ac4300c80e1d97a0aa12986c3868e850e2d746c973e81e39313d373142c3b0d94be7b496eba51487cbfd610bfc3c458425e007259a5361cc0902801189a729bfbe8a2147f0d5bbeca96e3ecb597220b3dee27197b4ae126fe40abdf9e082c40ea4b3cf9c1e22f18eff14d768c616dbdb2629b1953beb1a2a47308aadc145b650633ca8ecf2f7882ee937f06fa3ad387411724e7fcfd9e2c1851f7bee736dcbf731f4753d4bdd6492f38ca6e2dfcc17f000000ffff5eccce02f1000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Summon scaffold template", "../../templates/scaffold")
		b.SetResolver("Makefile", packr.Pointer{ForwardBox: gk, ForwardPath: "07bf76378c88abdaa6f6279178a74b28"})
		b.SetResolver("README.md", packr.Pointer{ForwardBox: gk, ForwardPath: "906ec5af0a8094a9d412299a6fa003ce"})
		b.SetResolver("assets/summon.config.yaml", packr.Pointer{ForwardBox: gk, ForwardPath: "54928eced2dca3a3ac53767040663e39"})
		b.SetResolver("go.mod", packr.Pointer{ForwardBox: gk, ForwardPath: "215e3cf9e27fb979ef10ff27f68b300f"})
		b.SetResolver("{{.SummonerName}}/summon{{.go}}", packr.Pointer{ForwardBox: gk, ForwardPath: "cb35e626a2c5a9c15406259f882a5aa2"})
	}()

	return nil
}()
